language: cpp
compiler:
  - clang
  - gcc

# Setup different environments to test
env:
  - CPP14=0
  - CPP14=1

before_script:  
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  email:
    recipients: vstrisovsky@gmail.com
    on_success: change
    on_failure: always