language: cpp
compiler:
  - gcc

#  - clang

# Setup different environments to test
env:
  - CPP14=0
  - CPP14=1

before_install:
  # CMake
  - wget -q -O cmake-3.2.3.tar.gz http://www.cmake.org/files/v3.2/cmake-3.2.3.tar.gz
  - tar xzvf cmake-3.2.3.tar.gz
  # GCC / Clang (Needed until Travis CI updates to Ubuntu 14.04+)
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # update
  - sudo apt-get update -qq

install:
  # GCC
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq --force-yes g++-4.9; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi
  # CMake
  - cd cmake-3.2.3
  - ./bootstrap
  - make -j 2
  - sudo make install
  - cd ..
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

after_success:
  - make test

notifications:
  email:
    recipients: vstrisovsky@gmail.com
    on_success: change
    on_failure: always
