language: cpp
compiler:
  - clang
  - gcc

# Setup different environments to test
env:
  - CPP14=0
  - CPP14=1

before_install:
  - wget -q -O cmake-3.2.3 http://www.cmake.org/files/v3.2/cmake-3.2.3.tar.gz

install:
  - cd cmake-3.2.3
  - ./bootstrap
  - make -j 2
  - sudo make install
  - cd ..
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev

before_script:  
  - mkdir build
  - cd build
  - ./cmake-3.1.0-Linux-x86_64/bin/cmake ..

script: 
  - make

notifications:
  email:
    recipients: vstrisovsky@gmail.com
    on_success: change
    on_failure: always